/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/EhBbT9e1fFa
 */
import Link from "next/link"
import { Button } from "@/components/ui/button"
import { CardHeader, CardContent, Card } from "@/components/ui/card"

export function Component() {
  return (
    <>
      <header className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800">
        <Link href="#">
          <FocusIcon className="w-8 h-8" />
          <span className="sr-only">FrontForumFocus</span>
        </Link>
        <nav className="space-x-4">
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            About
          </Link>
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            Features
          </Link>
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            Pricing
          </Link>
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            Contact
          </Link>
        </nav>
        <Button className="px-6 py-2 text-sm text-white bg-blue-600 hover:bg-blue-500" variant="primary">
          Get Started
        </Button>
      </header>
      <main className="px-6 py-12 md:py-24 bg-white dark:bg-gray-800">
        <section className="space-y-8 text-center">
          <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
            Empower Your Impact with FrontForumFocus
          </h1>
          <p className="text-lg text-gray-600 dark:text-gray-300">
            Bring your skills and passion to the global stage. Join like-minded individuals in creating innovative
            solutions for a sustainable future.
          </p>
          <Button className="px-8 py-3 text-sm text-white bg-blue-600 hover:bg-blue-500" variant="primary">
            Start Now
          </Button>
        </section>
        <section className="mt-16 space-y-8">
          <h2 className="text-2xl font-bold text-center text-gray-900 dark:text-gray-100">Why FrontForumFocus?</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            <Card>
              <CardHeader>
                <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">Match with Projects</h3>
              </CardHeader>
              <CardContent>
                <p className="text-gray-600 dark:text-gray-300">
                  Our tool matches you to networks and projects based on your skills, passions, and education.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">Create & Collaborate</h3>
              </CardHeader>
              <CardContent>
                <p className="text-gray-600 dark:text-gray-300">
                  Work on existing projects or create new ones. Collaborate with peers globally.
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardHeader>
                <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">Track Your Impact</h3>
              </CardHeader>
              <CardContent>
                <p className="text-gray-600 dark:text-gray-300">
                  Measure the impact of your work and contribution towards the SDGs. Make your efforts count.
                </p>
              </CardContent>
            </Card>
          </div>
        </section>
      </main>
      <footer className="flex items-center justify-between px-6 py-4 bg-white dark:bg-gray-800">
        <p className="text-gray-600 dark:text-gray-300">© FrontForumFocus. All rights reserved.</p>
        <nav className="space-x-4">
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            Privacy Policy
          </Link>
          <Link className="text-gray-600 hover:text-gray-900 dark:text-gray-300 dark:hover:text-gray-50" href="#">
            Terms of Service
          </Link>
        </nav>
      </footer>
    </>
  )
}


function FocusIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="3" />
      <path d="M3 7V5a2 2 0 0 1 2-2h2" />
      <path d="M17 3h2a2 2 0 0 1 2 2v2" />
      <path d="M21 17v2a2 2 0 0 1-2 2h-2" />
      <path d="M7 21H5a2 2 0 0 1-2-2v-2" />
    </svg>
  )
}
